### ISSUE TITLE
"FlexiCubes + G-Shell" reconstruction failed with IndexError caused by the `nonzero_mask`

### ISSUE THREAD

**Issue by RainEggplant** [lzzcd001/GShell#3]
Thank you for sharing this great work! I'm having some issues running the "FlexiCubes + G-Shell" reconstruction demo. Could you please check it?

**Environment**
- Ubuntu 22.04
- Python 3.9.18, PyTorch 1.13.1, CUDA 11.7, tiny-cuda-nn 1.7
- nvdiffrast 0.3.1, kaolin 0.15.0, xatlas 0.0.9

**To reproduce**
1. Download the DeepFashion3D training & test data from the link in README.md and extract them to `data/deepfashion3d`.
2. Run the "FlexiCubes + G-Shell" reconstruction, e. g.,
   ```shell
     python train_gflexicubes_deepfashion.py --config configs/deepfashion_mc_80.json --index 0 --trainset_path data/deepfashion3d/deepfashion3d_training_data --testset_path data/deepfashion3d/deepfashion3d_test_data --o output/deepfashion3d/fc80
   ```
3. The training fails with error (see the log below)

**Log**
<details>
<summary>Click to toggle the content</summary>

```
Detected CUDA files, patching ldflags
Emitting ninja build file /data/user/projects/3d_generation/GShell/render/optixutils/build/build.ninja...
Building extension module optixutils_plugin...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module optixutils_plugin...
Config / Flags:
---------
config configs/deepfashion_mc_80.json
iter 5000
batch 2
spp 1
layers 1
train_res [1024, 1024]
display_res [1024, 1024]
texture_res [1024, 1024]
display_interval 0
save_interval 100
learning_rate [0.03, 0.005]
min_roughness 0.08
custom_mip False
random_textures True
background white
loss logl1
out_dir output/deepfashion3d/fc80
ref_mesh data/spot/spot.obj
base_mesh None
validate True
n_samples 24
bsdf pbr
denoiser bilateral
denoiser_demodulate True
index 0
trainset_path data/deepfashion3d/deepfashion3d_training_data
testset_path data/deepfashion3d/deepfashion3d_test_data
msdf_reg_open_scale 1e-06
msdf_reg_close_scale 3e-06
mtl_override None
gshell_grid 80
mesh_scale 1.4
envlight data/irrmaps/aerodynamics_workshop_2k.hdr
env_scale 2.0
probe_res 256
learn_lighting True
display [{'latlong': True}]
transparency False
lock_light False
lock_pos False
sdf_regularizer 0.2
laplace relative
laplace_scale 6000
pre_load True
no_perturbed_nrm False
decorrelated False
kd_min [0.0, 0.0, 0.0, 0.0]
kd_max [1.0, 1.0, 1.0, 1.0]
ks_min [0, 0.001, 0.0]
ks_max [0, 1.0, 1.0]
nrm_min [-1.0, -1.0, 0.0]
nrm_max [1.0, 1.0, 1.0]
clip_max_norm 0.0
cam_near_far [0.1, 1000.0]
lambda_kd 0.1
lambda_ks 0.05
lambda_nrm 0.025
lambda_nrm2 0.25
lambda_chroma 0.0
lambda_diffuse 0.15
lambda_specular 0.0025
random_lgt False
normal_only False
use_img_2nd_layer False
use_depth False
use_depth_2nd_layer False
use_tanh_deform False
use_sdf_mlp True
use_msdf_mlp False
use_eikonal True
sdf_mlp_pretrain_steps 10000
use_mesh_msdf_reg True
sphere_init False
sphere_init_norm 0.5
pretrained_sdf_mlp_path ./data/pretrained_mlp_64_deeper.pt
n_hidden 6
d_hidden 256
n_freq 6
skip_in [3]
use_float16 False
visualize_watertight False
local_rank 0
multi_gpu False
boxscale [1, 1, 1]
aabb [-1, -1, -1, 1, 1, 1]
---------
DatasetNERF: 72 images with shape [1024, 1024]
DatasetNERF: 72 images with shape [1024, 1024]
DatasetNERF: 200 images with shape [1024, 1024]
/data/user/miniconda3/envs/gshell/lib/python3.9/site-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /opt/conda/conda-bld/pytorch_1670525539683/work/aten/src/ATen/native/TensorShape.cpp:3190.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Cuda path /usr/local/cuda-11.8
End of OptiXStateWrapper
FlexiCubes grid min/max -0.699999988079071 0.699999988079071
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10000/10000 [18:30<00:00,  9.00it/s]
sdf net trained with loss: tensor(7.3609e-08, device='cuda:0', grad_fn=<MeanBackward0>)
Encoder output: 32 dims
Traceback (most recent call last):
  File "/data/user/projects/3d_generation/GShell/train_gflexicubes_deepfashion.py", line 691, in <module>
    geometry, mat = optimize_mesh(denoiser, glctx, geometry, mat, lgt, dataset_train, dataset_validate,
  File "/data/user/projects/3d_generation/GShell/train_gflexicubes_deepfashion.py", line 425, in optimize_mesh
    img_loss, depth_loss, reg_loss = geometry.tick(
  File "/data/user/projects/3d_generation/GShell/geometry/gshell_flexicubes_geometry.py", line 246, in tick
    opt_mesh_dict = self.render(glctx, target, lgt, opt_material,
  File "/data/user/projects/3d_generation/GShell/geometry/gshell_flexicubes_geometry.py", line 212, in render
    opt_mesh_dict = self.getMesh(opt_material)
  File "/data/user/projects/3d_generation/GShell/geometry/gshell_flexicubes_geometry.py", line 179, in getMesh
    verts, faces, reg_loss, extra = self.gflexicubes(v_deformed, sdf, msdf, self.indices, self.grid_res,
  File "/data/user/projects/3d_generation/GShell/geometry/gshell_flexicubes.py", line 213, in __call__
    vertices_open, faces_open, nus_open_stopvgd, nus_boundary_stopvgd = self._triangulate_msdf(vertices, faces, nus, nus_stopvgd)
  File "/data/user/projects/3d_generation/GShell/geometry/gshell_flexicubes.py", line 577, in _triangulate_msdf
    msdf_zero_crossing = self._linear_interp_nonan(nu_cut_edges_fx2, vertices_cut_edges_fx2)
  File "/data/user/projects/3d_generation/GShell/geometry/gshell_flexicubes.py", line 373, in _linear_interp_nonan
    scale[nonzero_mask] = edges_weight[nonzero_mask] / denominator[nonzero_mask]
IndexError: The shape of the mask [27, 1, 1] at index 1 does not match the shape of the indexed tensor [27, 2, 1] at index 1
OptiXStateWrapper destructor
```
</details>

**Other information**
The "Tetrahedral grid + G-Shell" version works fine.

**Comment by lzzcd001** [comment]
Thank you for pointing this bug out -- we have fixed it in the latest commit.

**Comment by RainEggplant** [comment]
@lzzcd001 Thanks for your quick response! I updated the code but met another problem. The FlexiCubes could not reconstruct valid geometry (see the images below).

**img_pass1_000000.png**
![img_pass1_000000](https://github.com/lzzcd001/GShell/assets/20147921/f64e54e6-38ea-4192-88d6-049c5874ca94)

**img_pass1_000031.png**
![img_pass1_000031](https://github.com/lzzcd001/GShell/assets/20147921/3d08b8d2-7f2a-47ec-b347-e267cf7d7b3e)

For some instances (such as 30), it eventually reported an error:

```
(...)
FlexiCubes grid min/max -0.699999988079071 0.699999988079071
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10000/10000 [18:29<00:00,  9.02it/s]
sdf net trained with loss: tensor(6.4341e-08, device='cuda:0', grad_fn=<MeanBackward0>)
Encoder output: 32 dims
Loading extension module renderutils_plugin...
iter=    0, img_loss=0.881366, depth_loss=0.000000, reg_loss=0.285457, lr=0.02999, time=36559.4 ms, rem=50.78 h
iter=   10, img_loss=0.743729, depth_loss=0.000000, reg_loss=0.284241, lr=0.02985, time=1432.6 ms, rem=1.99 h
iter=   20, img_loss=0.593159, depth_loss=0.000000, reg_loss=0.283748, lr=0.02971, time=905.9 ms, rem=1.25 h
(...)
iter= 3200, img_loss=0.621920, depth_loss=0.000000, reg_loss=0.023170, lr=0.00687, time=855.0 ms, rem=25.65 m
iter= 3210, img_loss=0.642001, depth_loss=0.000000, reg_loss=0.024796, lr=0.00684, time=787.9 ms, rem=23.51 m
Traceback (most recent call last):
  File "/data/user/projects/3d_generation/GShell/train_gflexicubes_deepfashion.py", line 692, in <module>
    geometry, mat = optimize_mesh(denoiser, glctx, geometry, mat, lgt, dataset_train, dataset_validate,
  File "/data/user/projects/3d_generation/GShell/train_gflexicubes_deepfashion.py", line 425, in optimize_mesh
    img_loss, depth_loss, reg_loss = geometry.tick(
  File "/data/user/projects/3d_generation/GShell/geometry/gshell_flexicubes_geometry.py", line 246, in tick
    opt_mesh_dict = self.render(glctx, target, lgt, opt_material,
  File "/data/user/projects/3d_generation/GShell/geometry/gshell_flexicubes_geometry.py", line 212, in render
    opt_mesh_dict = self.getMesh(opt_material)
  File "/data/user/projects/3d_generation/GShell/geometry/gshell_flexicubes_geometry.py", line 179, in getMesh
    verts, faces, reg_loss, extra = self.gflexicubes(v_deformed, sdf, msdf, self.indices, self.grid_res,
ValueError: not enough values to unpack (expected 4, got 3)
``` 

Could you please look into it?

**Comment by lzzcd001** [comment]
Thanks for your report -- we have pushed the bug fix and verified that it works on our side. Please let us know if the problem persists.

**Comment by RainEggplant** [comment]
Thanks! It's now working.
